from pathlib import Path

import nbformat
import pytest
from nbconvert.preprocessors import ExecutePreprocessor


def test_example_usage_notebook():
    """
    Reads, executes, and checks the example_usage notebook for errors.
    """
    notebook_path = Path(__file__).parent / "example_usage.ipynb"
    notebook_dir = notebook_path.parent

    with open(notebook_path) as f:
        nb = nbformat.read(f, as_version=4)

    # This tells the executor to run the notebook from within its own directory.
    ep = ExecutePreprocessor(
        timeout=5400,
        startup_timeout=300,  # Increase startup timeout to 5 minutes
        kernel_name="ga_env",
        cwd=notebook_dir,
    )

    try:
        # Execute the notebook.
        ep.preprocess(nb, {"metadata": {"path": str(notebook_dir)}})
    except Exception as e:
        # If the notebook fails, this will raise a more informative error.
        pytest.fail(f"Error executing notebook {notebook_path.name}: \n{e}")


def test_post_hoc_evaluation_notebook():
    """
    Reads, executes, and checks the post_hoc_evaluation notebook for errors.
    This depends on results generated by the example_usage test.
    """
    notebook_path = Path(__file__).parent / "post_hoc_evaluation.ipynb"
    notebook_dir = notebook_path.parent

    with open(notebook_path) as f:
        nb = nbformat.read(f, as_version=4)

    # This tells the executor to run the notebook from within its own directory.
    ep = ExecutePreprocessor(
        timeout=5400,
        startup_timeout=300,
        kernel_name="ga_env",
        cwd=notebook_dir,
    )

    try:
        # Execute the notebook.
        ep.preprocess(nb, {"metadata": {"path": str(notebook_dir)}})
    except Exception as e:
        # If the notebook fails, this will raise a more informative error.
        pytest.fail(f"Error executing notebook {notebook_path.name}: \n{e}")
